/*
 * generated by Xtext
 */
package com.wellnr.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BashDSLUiModule extends com.wellnr.ui.AbstractBashDSLUiModule {
	public BashDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
