/*
 * generated by Xtext
 */
package com.wellnr;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BashDSLRuntimeModule extends com.wellnr.AbstractBashDSLRuntimeModule {

}
