/*
 * generated by Xtext
 */
package com.wellnr;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BashDSLStandaloneSetup extends BashDSLStandaloneSetupGenerated{

	public static void doSetup() {
		new BashDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

