/*
 * generated by Xtext
 */
package com.wellnr.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractBashDSLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.wellnr.bashDSL.BashDSLPackage.eINSTANCE);
		return result;
	}
}
