/*
 * generated by Xtext
 */
package com.wellnr.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.wellnr.ui.internal.BashDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BashDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BashDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BashDSLActivator.getInstance().getInjector(BashDSLActivator.COM_WELLNR_BASHDSL);
	}
	
}
