/**
 * generated by Xtext
 */
package com.wellnr.validation;

import com.wellnr.validation.AbstractBashDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class BashDSLValidator extends AbstractBashDSLValidator {
}
