/**
 * generated by Xtext
 */
package com.wellnr.ui.contentassist;

import com.wellnr.ui.contentassist.AbstractBashDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class BashDSLProposalProvider extends AbstractBashDSLProposalProvider {
}
